### ISSUE TITLE
关于ASTableNode/ASCollectionNode刷新闪一下的问题。

### ISSUE THREAD

**Issue by peak77** [didez/ASDK-Demo#1]
进行局部或者整体刷新的时候，总是会闪一下，作者在用的过程中是怎么解决的。

**Comment by diaotongt** [comment]
> 进行局部或者整体刷新的时候，总是会闪一下，作者在用的过程中是怎么解决的。

网上找了好多demo，发现好像是如果是本地数据，闪动不大，如果是自己请求网络数据解析出来的闪动就很大。不知道你是不是这样。你的闪动解决了吗 ？求告知。

**Comment by snilwx** [comment]
这个网络的资源链接是不是不存在了，图片数据显示不出来呢
